version: '3'

services:
  backend:
    build: 
      context: ./
      
    depends_on:
      - mongo
      - redis
    env_file:
      - .env 
    environment:
      DB_CONN_STRING: "mongodb://admin:admin@mongo:27017"
      REDIS_OM_URL: "redis://redis:6379"
    volumes:
      - ./backend:/pay-buddy-Backend
      - /pay-buddy-Backend/node_modules
    ports:
      - 3000:3000

  mongo:
    image: mongo:4.4.29
    container_name: paybudyyArchive
    restart: always
    env_file:
     - .env

  redis:
    image: redis:latest
    restart: always
    
    

volumes:
  mongo-data:
